#!/bin/bash

function cleanup() {
    killall mpirun
    killall mallob
    killall mallob_sat_process
    pkill -9 mpi
    pkill -9 mallob
    pkill -9 mallob_sat_process
    rm -rf /dev/shm/edu.kit.mallob.* /tmp/mallob* /competition/mallob_thread_trace_*
    killall dratify
    killall lrat-check 
    killall compress
    killall preprocess-cnf
    killall compose-proofs
    killall renumber-proofs
    killall decompress
    killall drat-trim
}

if ls /competition|grep -q mallob_thread_trace; then
    echo "Logging created thread traces"
    for f in /competition/mallob_thread_trace_*; do 
        echo ""
        echo "*************************************"
        echo "Thread trace $f"
        cat $f
        echo "*************************************"
    done
fi

echo "Cleaning up: Killing all mpi processes"
cleanup 2>&1 > /dev/null

echo "Cleaning up previous proofs..."
rm -rf "/logs"
